### ISSUE TITLE
Throttle alerts when not printing

### ISSUE THREAD

**Issue by SuperTrollMan** [OctoFarm/OctoFarm#1087]
### OctoFarm Version

1.2.8

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

pm2

### Operating System

Ubuntu 20.04.4

### OctoPrint Plugins

Bed Visualizer (1.1.1), Cancel Objects (0.4.7), Consolidated Tabs (1.0.1), Cost Estimation (3.5.0), Dashboard (1.19.8), DisplayLayerProgress Plugin (1.28.0), Filament Manager (1.9.1), Octoslack (2.2.0), PrintJobHistory (1.17.0), PrintTimeGenius Plugin (2.2.8), Slicer Thumbnails (1.0.0), TP-Link Smartplug (1.0.2)

### Location of the problem

Web Interface

### Description of the problem

```markdown
When nothing is printing, the alert is listed "Printer connection is throttled!"
When something is printing, they go away.
```

### Steps taken to reproduce

1. Start Octofarm
2. Ensure connections to OP are up
3. Don't print anything

### What did you expect to happen

[octofarm_dump-6-15-2022-10-44-32 AM.zip](https://github.com/OctoFarm/OctoFarm/files/8908583/octofarm_dump-6-15-2022-10-44-32.AM.zip)
![Screenshot 2022-06-15 184912](https://user-images.githubusercontent.com/95956617/173809948-5c690e9a-460c-465f-b6aa-22181f7d9457.png)

**Comment by NotExpectedYet** [comment]
I do wonder if something has changed on the OP side of things as I've not changed the logic here in a while. Thanks for the report will check!

**Comment by NotExpectedYet** [comment]
Confusingly I cannot reproduce this. 

OP is certainly still sending message in the Operational state and I tested the check throttle rate function with 2000ms messages then drops down to 500ms after 60 seconds and it correctly lowers the rate so I don't think it's the actual function. Your printers are in states where the messages are correctly checked as well, 

I have a question though, does this persist and continue if you restart OP? 

I ask because I had an instance here doing exactly the same, it would always bump right back up to level 3 throttle. I couldn't get it to do it after / before a print as you but the instance that was doing it hadn't been restarted after a plugin had been installed (totally irrelevant, think more just not restarted in a while) and as soon as I restarted it all the socket messages have starting coming in, in a more timely fashion. Just wondering if you see the same more than anything?

**Comment by SuperTrollMan** [comment]
I restarted all 3x RPI's yesterday, so <24 hours uptime.
The OF instance has probably been up for about the same, maybe 48 hours max.

I restarted the top OP in this screenshot just now to double check, and it comes and goes as its establishing the connection, then levels out to 3-5
![Screenshot 2022-06-16 211040](https://user-images.githubusercontent.com/95956617/174077125-c02daaba-64cf-4445-b7e1-9e0a2e61a0ba.png)
.

**Comment by NotExpectedYet** [comment]
Yeah mine have slowly crept back up. Looking at the sockets I keep getting a random socket message going over the limit. It currently responds to that as it ends up been the highest in the last 20 checked messages. I'll see if I can iron out the messages a bit better with an average rather than the max.
