### ISSUE TITLE
Camera view collapsed when accessing OctoFarm from local DNS name

### ISSUE THREAD

**Issue by HeyRay2** [OctoFarm/OctoFarm#1159]
### OctoFarm Version

Client: 1.4.1 | Server 1.4.3

### OctoPrint Version(s)

1.8.1

### pm2 or docker?

docker

### Operating System

Ubuntu Server

### Location of the problem

Web Interface

### Description of the problem

```markdown
When accessing OctoFarm from a local DNS name (example: octofarm.mydomain.com) the camera views are collapsed.

Accessing the same OctoFarm instance from the IP address results in the camera views being properly rendered.
```

### Steps taken to reproduce

1. Create a local DNS entry for OctoFarm (example: octofarm.mydomain.com)
2. Access OctoFarm from local DNS name
3. Go to "Camera" view
4. Confirm that camera views are collapsed
5. Access OctoFarm from IP address
6. Go to "Camera" view
7. Confirm that camera vies are properly rendered

![image](https://user-images.githubusercontent.com/21136720/177451185-2c0672f3-db9a-4fe6-a540-1982ace1d804.png)

### What did you expect to happen

Camera views should be properly rendered even when accessing OctoFarm from a local DNS entry

### To avoid the problem I had to

Access OctoFarm by IP address instead of local DNS entry

**Comment by NotExpectedYet** [comment]
![image](https://user-images.githubusercontent.com/61137988/177461068-72cefd19-d2ad-4707-a8c2-e4c09e96cff9.png)

It's HTTPS, if your camera's are http accessible then it won't route due to a browser limitation. 

I recommend updating to the latest 1.5.1 version and then turning on the camera proxy in the settings. It will route through your DNS name properly then. 

v1.4.3 of the server disabled this functionality been automatic as there was a limitation with 4 streams for some reason. I've now fixed this and improved the functionality but left it up to the user to enable. 

You can find the setting here: 

![image](https://user-images.githubusercontent.com/61137988/177461562-53772a91-5d1d-43f9-bacf-8ebdcecb300b.png)

**Comment by HeyRay2** [comment]
Thanks @NotExpectedYet.

The OctoFarm Docker images doesn't appear to be updated to 1.5.1 yet (pulling "Latest" keeps pulling 1.4.3), but I will give your suggestion a shot after I'm able pull down this latest version.

**Comment by NotExpectedYet** [comment]
> Thanks @NotExpectedYet.
> 
> The OctoFarm Docker image doesn't appear to be updated to 1.5.1 yet (pulling "Latest" keeps pulling 1.4.3), but I will give your suggestion a shot after I'm able pull down this latest version.

Hmm weird, let me check if my automation ran.

**Comment by NotExpectedYet** [comment]
My builds broke sometime recently. Will take a look and let you know, cheers for pointing that out!

**Comment by NotExpectedYet** [comment]
Docker is now built so closing this.

**Comment by HeyRay2** [comment]
Excellent! Thanks!

**Comment by NotExpectedYet** [comment]
Do let me know if there any other issues :)
