### ISSUE TITLE
History failing to generate due to missing settings

### ISSUE THREAD

**Issue by Gagonjh** [OctoFarm/OctoFarm#414]
### To better help the developer understand your issue, please fill in the information below. Failing to do so will waste the developer and your own time in sorting the issue. Thanks!

**Client or Server side error** 
Server side

**Describe the bug**
The print history is empty even after a successful print. The Filament usage 
didn't update. But I think that's a side effect. The Connection work fine for both printers and I can use them normally.

**Screenshots**
![Octofarm_History](https://user-images.githubusercontent.com/49719775/113512956-79a5a100-9567-11eb-95f2-0419f23eed7e.PNG)
![Octofarm_Filaments](https://user-images.githubusercontent.com/49719775/113512966-84603600-9567-11eb-9e9c-771d7069a007.PNG)
![OctoFarm_Panel](https://user-images.githubusercontent.com/49719775/113512968-86c29000-9567-11eb-9a8b-13336a1d6b6e.PNG)

**System**
Raspberry Pi 4 2GB (Server and on one 3D printer)
Raspberry Pi 3 1GB
Klipper as Firmware

**Versions (please complete the following information):**
Ubuntu (20.04.2 LTS)
OctoFarm (1.1.12)
Octopi (0.18.0)
Octoprint (1.5.3)
Bed Visualizer (1.0.1)
Marlin GCode Documentation (0.12.0)
OctoKlipper (0.3.7)
Preheat Button (0.7.2)
PrintTimeGenius Plugin (2.2.7)
PrusaSlicer Thumbnails (0.1.4)
Themeify (1.2.2)

**Additional context**
The 3d printers were set up last week. OctoFarm yesterday on a clean system.

[OctoFarm-HistoryCollection.log](https://github.com/OctoFarm/OctoFarm/files/6254804/OctoFarm-HistoryCollection.log)

**Comment by NotExpectedYet** [comment]
Ahh my old settings bug / goof. 

You should be able to fix this by saving system settings in System -> Server then press the blue save button. You won't need to change anything. 

My appolgise I'd thought that was all fixed but obviously not.

Let me know if that doesn't resolve but it should. 

I'll leave this ticket open regardless because I'm currently giving history a massive overhaul which will solve this once and for all :)
