### ISSUE TITLE
PrinterClean `x of undefined` when you start a new database, don't add printers and restart

### ISSUE THREAD

**Issue by NotExpectedYet** [OctoFarm/OctoFarm#567]
### Description of the problem

```bash
Currently when you start a new database on development then you get a unhandled error event as it's trying to find 
`heatMap[i].data[lastInArray].x` when `(heatMap[i].data[lastInArray]` doesn't exist.
```

### Reproduction of the problem

```bash
...
```

**Comment by davidzwa** [comment]
We've come to the conclusion that the problem lies in a race-condition caused by the code at the bottom of `index.js` in combination with the code in `app-core.js:serveOctoFarmNormally`.

The bottom of index.js contains code which runs in a 2500 ms loop, but apparently isnt done quickly enough on all systems or it is skipped because mongoose is not ready to connect yet.
The code calls `PrinterClean.sortCurrentOperations(printersInformation);` which calls `PrinterClean.Heatmapping` after a certain counter only, but this counter is 17280 by default (run at start). So all in all combined can result in heatmap being incorrectly saved to database before using it in `await PrinterClean.initFarmInformation();`

**Comment by NotExpectedYet** [comment]
Good investigation. 

I gather we should open another ticket for reorganising the timers and what not for start up and beyond.
