### ISSUE TITLE
File Manager statistics are not generated on server start

### ISSUE THREAD

**Issue by maxxeweb** [OctoFarm/OctoFarm#837]
### Description of the problem

```bash
...
When I open File Manager i get 
UNKNOWN ERROR (999):
Please report this error to OctoFarm Issues!
Cannot read properties of undefined (reading 'length')
```

### Reproduction of the problem

```bash
..FILE INFO
LINE: undefined
COL: undefined
STACK:
UNKNOWN: Cannot read properties of undefined (reading 'length') at http://localhost:4000/assets/dist/file-manager.runner.min.js:2:191465 at Array.forEach () at Function.drawPrinterList (http://localhost:4000/assets/dist/file-manager.runner.min.js:2:189592) at async Function.init (http://localhost:4000/assets/dist/file-manager.runner.min.js:2:193883).
```

**Comment by maxxeweb** [comment]
This seems to stop Multi Load 

cannot set multi printers with same job

**Comment by NotExpectedYet** [comment]
Issues for development issues are not reported here, these are for master branch issues. The development version currently has those two features broken because I'm still working through the websocket changes. 

Please either come to the developer discussions on discord, or add the issue to the lastest RC discussion list but I'm already aware of these two.

**Comment by NotExpectedYet** [comment]
https://github.com/OctoFarm/OctoFarm/discussions/779

Added here

**Comment by NotExpectedYet** [comment]
Changing how I'm doing this now

**Comment by NotExpectedYet** [comment]
Hi this should be fixed now. Multi-Upload is disabled until I get around to cleaning it up though :) will close this. Multi-Upload is on my list of to-do once I've sorted filament manager.
